---
# tasks file for role_container
#


- name: Create a network with custom IPAM config
  docker_network:
    name: network_project
    ipam_config:
      - subnet: "{{__root_network}}.0/24"
        gateway: "{{__root_network}}.254"
        

- name: Create a custom image from ubuntu with user=ugeek and minimum packages
  docker_image:
    name: i_custom_ubuntu
    build:
      path: ./role_container/build_01
    source: build
    force_absent: yes 


- name: Create a container for elastic, based on custom image created above
  docker_container:
    name: c_elastic
    image: i_custom_ubuntu
    ports: "9200:9200"
    detach: yes
    interactive: yes
    tty: yes
    recreate: no
    hostname: elastichost
    networks:
      - name: network_project
        ipv4_address: "{{ __ip_elastic }}"


- name: Create a container for Nginx, based on custom image created above
  docker_container:
    name: c_nginx
    image: i_custom_ubuntu
    ports: "80:80"
    detach: yes
    interactive: yes
    tty: yes
    recreate: no
    hostname: nginxhost
    networks:
      - name: network_project
        ipv4_address: "{{ __ip_nginx }}"


- name: Create a container for Kibana, based on custom image created above
  docker_container:
    name: c_kibana
    image: i_custom_ubuntu
    ports: "5601:5601"
    detach: yes
    interactive: yes
    tty: yes
    recreate: no
    hostname: kibanahost
    networks:
      - name: network_project
        ipv4_address: "{{ __ip_kibana }}"



